version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  website:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  proxy:
    ports:
      - "5000:80"
