version: '3.4'

services:
  api:
    image: local/api
    build:
      context: .
      dockerfile: Api/Dockerfile

  website:
    image: local/website
    build:
      context: .
      dockerfile: RazorPrecompilationTest/Dockerfile

  proxy:
    image: local/proxy
    build:
      context: .
      dockerfile: nginx/Dockerfile