version: '3.4'

services:
  api:
    container_name: razor-test-api
    build:
      context: .
      dockerfile: Api/Dockerfile

  api-warmup:
    image: razor-test/warmup
    container_name: razor-test-api-warmup
    build:
      context: .
      dockerfile: warmup/Dockerfile
    depends_on:
      - "api"
    command: ["./wait-for-it.sh", "-s", "api:80/api/healthcheck", "--", "curl", "-o /dev/null", "-w %{time_total}\\n", "http://api/api/values"]

  website:
    container_name: razor-test-website
    build:
      context: .
      dockerfile: RazorPrecompilationTest/Dockerfile

  #website-warmup:
  #  image: razor-test/warmup
  #  container_name: razor-test-website-warmup
  #  build:
  #    context: .
  #    dockerfile: warmup/Dockerfile
  #  depends_on:
  #    - "website"
  #  command: ["bash", "./wait-for-it.sh", "website:80/healthcheck", "--", "curl", "-o /dev/null", "-w %{time_total}\\n", "http://website/account/login"]

  proxy:
    container_name: razor-test-proxy
    build:
      context: .
      dockerfile: nginx/Dockerfile