version: '3.4'

services:
  api:
    image: local/api
    build:
      context: .
      dockerfile: Api/Dockerfile

  website:
    image: local/razorprecompilationtest
    build:
      context: .
      dockerfile: RazorPrecompilationTest/Dockerfile

  nginx:
    image: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile

